# Generated by Django 6.0.6 on 2026-06-23 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="tag-django",
                        help_text="tag-django | tag-python | tag-drf | tag-pg | tag-docker",
                        max_length=20,
                        verbose_name="CSS klassi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Teg"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Teg",
                "verbose_name_plural": "Teglar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Haqida")),
                (
                    "avatar_letter",
                    models.CharField(
                        blank=True,
                        help_text="Frontendda doirachaga chiqadigan harf (avtomatik to'ldiriladi)",
                        max_length=1,
                        verbose_name="Avatar harfi",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Masalan: Senior Django Developer",
                        max_length=100,
                        verbose_name="Lavozim",
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Muallif",
                "verbose_name_plural": "Mualliflar",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Sarlavha")),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=350, verbose_name="Qisqa tavsif"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/%Y/%m/%d/",
                        verbose_name="Maqola rasmi",
                    ),
                ),
                (
                    "content",
                    models.TextField(verbose_name="Mazmun (HTML yoki Markdown)"),
                ),
                (
                    "code_snippet",
                    models.TextField(
                        blank=True,
                        help_text="Blog ro'yxatidagi kartada chiqadigan qisqa kod namunasi",
                        verbose_name="Kod snippet (karta uchun)",
                    ),
                ),
                (
                    "code_snippet_lang",
                    models.CharField(
                        blank=True,
                        default="python",
                        max_length=30,
                        verbose_name="Kod tili",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Qoralama"), ("published", "Nashr etilgan")],
                        default="draft",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Tanlangan (featured)?"
                    ),
                ),
                (
                    "read_time",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Avtomatik hisoblanmaydi — qo'lda kiriting",
                        verbose_name="O'qish vaqti (daqiqa)",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Ko'rishlar soni"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Nashr sanasi"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.author",
                        verbose_name="Muallif",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.category",
                        verbose_name="Kategoriya",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="articles",
                        to="blog.tag",
                        verbose_name="Teglar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maqola",
                "verbose_name_plural": "Maqolalar",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("like", "Like"), ("dislike", "Dislike")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="blog.article",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="blog_articl_slug_cc8df7_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "-published_at"], name="blog_articl_status_47bfec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "status"], name="blog_articl_categor_ff847e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("article", "ip_address")},
        ),
    ]
